version: "3.8"
services:
  db:
    image: mysql:8.0.33
    environment:
      MYSQL_DATABASE: exchange-test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: roottest
    ports:
      - "3306:3306"
