version: "3.8"
services:
  db:
    image: mysql:8.0.33
    environment:
      MYSQL_DATABASE: exchange
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    volumes:
      - exchange-system:/var/lib/mysql
    networks:
      - exchange-system
  exchange-api:
    restart: always
    build:
      context: .
    ports:
      - "8080:8080"
      - "10000:10000"
    environment:
      DB_NAME: exchange
      DB_USER: user
      DB_PASSWORD: pass
      DB_PORT: 3306
      DB_HOST: db
    depends_on:
      - db
    networks:
      - exchange-system

networks:
  exchange-system:
volumes:
  exchange-system:
