// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package handler

import (
	"context"
	"github.com/dotdak/exchange-system/infrastructure"
	"github.com/dotdak/exchange-system/repo"
)

// Injectors from build.go:

func BuildHandler(ctx context.Context) (Handler, error) {
	dbConfig := infrastructure.NewDbConfig()
	db, err := infrastructure.NewMysqlDb(dbConfig)
	if err != nil {
		return nil, err
	}
	logger := infrastructure.NewLogger()
	wagerRepo := repo.NewWagerRepo(db, logger)
	buyRepo := repo.NewBuyRepo(db, logger)
	handler := NewHandler(wagerRepo, buyRepo, logger, db)
	return handler, nil
}
