// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package handler

import (
	"context"
	"github.com/dotdak/exchange-system/infrastructure"
	"github.com/dotdak/exchange-system/repo"
)

// Injectors from build.go:

func BuildHandler(ctx context.Context) (Handler, error) {
	dbConfig := infrastructure.NewDbConfig()
	db, err := infrastructure.NewMysqlDb(dbConfig)
	if err != nil {
		return nil, err
	}
	wagerRepo := repo.NewWagerRepo(db)
	buyRepo := repo.NewBuyRepo(db)
	handler := NewHandler(wagerRepo, buyRepo)
	return handler, nil
}
