name: Go
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: golang:latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up Git
        run: |
          git config --global init.defaultBranch main
          git config --global --add safe.directory /__w/exchange-system/exchange-system
      - name: Build
        run: go build -v ./...
  lint:
    name: Lint
    runs-on: ubuntu-latest
    container:
      image: golang:latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Install tools
        run: make install
      - name: Lint
        run: make lint
  generate:
    name: Regenerate files
    runs-on: ubuntu-latest
    container:
      image: golang:latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up Git
        run: |
          git config --global init.defaultBranch main
          git config --global --add safe.directory /__w/exchange-system/exchange-system
      - name: Install tools
        run: make install && go mod tidy
      - name: Regenerate files
        run: make generate
      - name: Check for a diff
        run: git diff --exit-code
  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest
    container:
      image: golang:latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Test
        run: go test ./...
  integration-test:
    name: Integration Tests
    runs-on: ubuntu-latest
    container:
      image: golang:latest
    services:
      db:
        image: mysql:8.0.33
        ports: 3306:3306
        environment:
          MYSQL_DATABASE: exchange-test
          MYSQL_USER: test
          MYSQL_PASSWORD: test
          MYSQL_ROOT_PASSWORD: roottest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Test
        run: go test -tags=integration ./... -v -count=1
